Machine.add(me.dir()+"sequencer.ck");
//Machine.add(me.dir()+"weightedRandomClass.ck");
//Machine.add(me.dir()+"makeScaleClass.ck");
Machine.add(me.dir()+"euclideanRhythms.ck");
//Machine.add(me.dir()+"binaryNums.ck");
//Machine.add(me.dir()+"cellularAutomata.ck");
//Machine.add(me.dir()+"ZynMidiOut.ck");
Machine.add(me.dir()+"hydrogenMidiOut.ck");
Machine.add(me.dir()+"score.ck");
